# QUESTION 321
# If you need to serve two different exceptions called Ex1 and Ex2 in 
# one except branch, you can write:
# siehe exceptions.py

# A. except Ex1 Ex2:
# B. except (Ex1, Ex2): # except(TypeError, ValueError): 
# C. except Ex1, Ex2:
# D. except Ex1+Ex2:

# LÃ¶sung: B